'\" t
.\"     Title: freefoam-extrudemesh
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-EXTRUDEMESH" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-extrudeMesh \- Extrude mesh from existing patch or from patch read from file\&.
.SH "SYNOPSIS"
.sp
\fBfreefoam extrudeMesh\fR [\-sourceCase \fI<source case name>\fR] [\-sourcePatch \fI<name of source patch to extrude>\fR] [\-mergeFaces] [\-surface \fI<Foam surface file>\fR] [\-srcDoc] [\-doc] [\-help] [\-sourceRoot \fI<directory containing the case>\fR] [\-case \fI<dir>\fR]
.SH "DESCRIPTION"
.sp
By default uses outwards facing normals, optionally flips faces\&.
.sp
Type of extrusion prescribed by run\-time selectable model\&.
.SH "OPTIONS"
.PP
\fB\-mergeFaces\fR
.RS 4
Merge faces for axisymmetric cases\&.
.RE
.PP
\fB\-sourceRoot\fR \fI<directory containing the case>\fR
.RS 4
Parent directory of the source case\&.
.RE
.PP
\fB\-sourceCase\fR \fI<source case name>\fR
.RS 4
Source case name\&.
.RE
.PP
\fB\-sourcePatch\fR \fI<name of source patch to extrude>\fR
.RS 4
Source patch\&.
.RE
.PP
\fB\-surface\fR \fI<Foam surface file>\fR
.RS 4
Specify surface file to extrude\&.
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "NOTE"
.sp
Merges close points so be careful\&.
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
