'\" t
.\"     Title: freefoam-graphreske
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-GRAPHRESKE" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-graphResKE \- Extract the residuals of k and epsilon at each time step
.SH "SYNOPSIS"
.sp
\fBfreefoam graphResKE\fR \fI<logFile>\fR
.SH "DESCRIPTION"
.sp
The utility extracts the residuals of the k and epsilon equations at each time step and writes them to \fIresidualKE\&.dat\fR\&. The file has the following format:
.sp
.if n \{\
.RS 4
.\}
.nf
Solver Performance
number of iterations
residual
0 0
0 0
<nGraphs>
k
0
<nK>
1\&.000000 <resK1>
2\&.000000 <resK2>
3\&.000000 <resK3>
4\&.000000 <resK4>
5\&.000000 <resK5>
\&.\&.\&.
epsilon
0
<nEpsilon>
1\&.000000 <resEpsilon1>
2\&.000000 <resEpsilon2>
3\&.000000 <resEpsilon3>
4\&.000000 <resEpsilon4>
5\&.000000 <resEpsilon5>
\&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
where \fI<nK>\fR and \fI<nEpsilon>\fR is the number of data points for \fIk\fR and \fIepsilon\fR, respectively\&. \fI<resKX>\fR and \fI<resEpsilonX>\fR are the residual at iteration \fIX\fR for \fIk\fR and \fIepsilon\fR\&.
.SH "OPTIONS"
.PP
\fI<logFile>\fR
.RS 4
A FreeFOAM log file (i\&.e\&. the screen\-output created by a FreeFOAM solver)
.RE
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
