'\" t
.\"     Title: freefoam-foamtoensightparts
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-FOAMTOENSIGHTPARTS" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-foamToEnsightParts \- Translates OpenFOAM data to Ensight format\&. An Ensight part is created for each cellZone and patch\&.
.SH "SYNOPSIS"
.sp
\fBfreefoam foamToEnsightParts\fR [\-index \fI<start>\fR] [\-latestTime] [\-noZero] [\-srcDoc] [\-noMesh] [\-doc] [\-time \fI<time>\fR] [\-constant] [\-ascii] [\-case \fI<dir>\fR] [\-help]
.SH "DESCRIPTION"
.sp
\fBTODO\fR write detailed description
.SH "OPTIONS"
.PP
\fB\-ascii\fR
.RS 4
Write Ensight data in ASCII format instead of "C Binary"
.RE
.PP
\fB\-noZero\fR
.RS 4
Exclude the often incomplete initial conditions\&.
.RE
.PP
\fB\-index\fR \fI<start>\fR
.RS 4
Ignore the time index contained in the time file and use a simple indexing when creating the
Ensight/data/## files\&.
.RE
.PP
\fB\-noMesh\fR
.RS 4
Suppress writing the geometry\&. Can be useful for converting partial results for a static geometry\&.
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-constant\fR
.RS 4
Include the constant directory\&.
.RE
.PP
\fB\-latestTime\fR
.RS 4
Only apply to the latest time step\&.
.RE
.PP
\fB\-time\fR \fI<time>\fR
.RS 4
Apply only to specified time\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "NOTE"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
no parallel data\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
writes to
\fIEnsight\fR
directory to avoid collisions with foamToEnsight\&.
.RE
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
