'\" t
.\"     Title: freefoam-foamtostarmesh
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-FOAMTOSTARMESH" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-foamToStarMesh \- Reads an OpenFOAM mesh and writes a pro\-STAR (v4) bnd/cel/vrt format\&.
.SH "SYNOPSIS"
.sp
\fBfreefoam foamToStarMesh\fR [\-help] [\-latestTime] [\-scale \fI<factor>\fR] [\-tri] [\-noZero] [\-surface] [\-srcDoc] [\-doc] [\-time \fI<time>\fR] [\-constant] [\-case \fI<dir>\fR] [\-noBnd]
.SH "DESCRIPTION"
.sp
\fBTODO\fR write detailed description
.SH "OPTIONS"
.PP
\fB\-noBnd\fR
.RS 4
Suppress writing the @c \&.bnd file\&.
.RE
.PP
\fB\-scale\fR \fI<factor>\fR
.RS 4
Specify an alternative geometry scaling factor\&. The default is
\fB1000\fR
(scale @em [m] to @em [mm])\&.
.RE
.PP
\fB\-surface\fR
.RS 4
Extract the surface of the volume mesh only\&. This can be useful, for example, for surface morphing in an external package\&.
.RE
.PP
\fB\-tri\fR
.RS 4
Extract a triangulated surface\&. The @b \-surface options is implicitly selected\&.
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-noZero\fR
.RS 4
Ignore time step 0\&.
.RE
.PP
\fB\-constant\fR
.RS 4
Include the constant directory\&.
.RE
.PP
\fB\-latestTime\fR
.RS 4
Only apply to the latest time step\&.
.RE
.PP
\fB\-time\fR \fI<time>\fR
.RS 4
Apply only to specified time\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "NOTE"
.sp
The cellTable information available in the files constant/cellTable and constant/polyMesh/cellTableId will be used if available\&. Otherwise the cellZones are used when creating the cellTable information\&. SEE ALSO
.sp
.if n \{\
.RS 4
.\}
.nf
Foam::cellTable, Foam::meshWriter and Foam::meshWriters::STARCD


SEE ALSO
.fi
.if n \{\
.RE
.\}
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
