'\" t
.\"     Title: freefoam-mapfields
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-MAPFIELDS" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-mapFields \- Maps volume fields from one mesh to another\&.
.SH "SYNOPSIS"
.sp
\fBfreefoam mapFields\fR \fI<source dir>\fR [\-parallelSource] [\-parallelTarget] [\-srcDoc] [\-doc] [\-help] [\-consistent] [\-case \fI<dir>\fR] [\-sourceTime \fI<scalar>\fR]
.SH "DESCRIPTION"
.sp
Maps volume fields from one mesh to another, reading and interpolating all fields present in the time directory of both cases\&. Parallel and non\-parallel cases are handled without the need to reconstruct them first\&.
.SH "OPTIONS"
.PP
\fI<source dir>\fR
.RS 4

\fBTODO\fR
Detailed description of argument\&.
.RE
.PP
\fB\-consistent\fR
.RS 4
Meshes are consistent\&.
.RE
.PP
\fB\-parallelSource\fR
.RS 4
The source case is decomposed\&.
.RE
.PP
\fB\-sourceTime\fR \fI<scalar>\fR
.RS 4
Time of the source\&.
.RE
.PP
\fB\-parallelTarget\fR
.RS 4
The target case is decomposed\&.
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
