'\" t
.\"     Title: freefoam-stitchmesh
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-STITCHMESH" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-stitchMesh \- \*(AqStitches\*(Aq a mesh\&.
.SH "SYNOPSIS"
.sp
\fBfreefoam stitchMesh\fR \fI<masterPatch>\fR \fI<slavePatch>\fR [\-perfect] [\-partial] [\-srcDoc] [\-doc] [\-overwrite] [\-help] [\-case \fI<dir>\fR]
.SH "DESCRIPTION"
.sp
Takes a mesh and two patches and merges the faces on the two patches (if geometrically possible) so the faces become internal\&.
.sp
Can do \- \fIperfect\fR match: faces and points on patches align exactly\&. Order might be different though\&. \- \fIintegral\fR match: where the surfaces on both patches exactly match but the individual faces not \- \fIpartial\fR match: where the non\-overlapping part of the surface remains in the respective patch\&.
.SH "OPTIONS"
.PP
\fI<masterPatch>\fR
.RS 4

\fBTODO\fR
Detailed description of argument\&.
.RE
.PP
\fI<slavePatch>\fR
.RS 4

\fBTODO\fR
Detailed description of argument\&.
.RE
.PP
\fB\-perfect\fR
.RS 4
The patches, vertices and face centres are perfectly aligned\&.
.RE
.PP
\fB\-partial\fR
.RS 4
The surface overlap only partialy\&.
.RE
.PP
\fB\-overwrite\fR
.RS 4
Overwrite existing data\&.
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "NOTE"
.sp
Is just a front\-end to perfectInterface/slidingInterface\&.
.sp
Comparable to running a meshModifier of the form (if masterPatch is called "M" and slavePatch "S"):
.sp
couple { type slidingInterface; masterFaceZoneName MSMasterZone slaveFaceZoneName MSSlaveZone cutPointZoneName MSCutPointZone cutFaceZoneName MSCutFaceZone masterPatchName M; slavePatchName S; typeOfMatch partial or integral }
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
