'\" t
.\"     Title: freefoam-infoexec
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-INFOEXEC" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-infoExec \- Interrogates a case and prints information to screen
.SH "SYNOPSIS"
.sp
\fBfreefoam infoExec\fR [\-keywords] [\-times] [\-help] [\-srcDoc] [\-doc] [\-case \fI<dir>\fR] [\-entry \fI<entry name>\fR] [\-dictionary \fI<dictionary name>\fR]
.SH "DESCRIPTION"
.sp
\fBTODO\fR write detailed description
.SH "OPTIONS"
.PP
\fB\-dictionary\fR \fI<dictionary name>\fR
.RS 4
Use specified dictionary\&.
.RE
.PP
\fB\-entry\fR \fI<entry name>\fR
.RS 4
Use specified entry from dictionary (parent:child notation)
.RE
.PP
\fB\-keywords\fR
.RS 4
List keywords in the dictionary\&.
.RE
.PP
\fB\-times\fR
.RS 4
List all time steps\&.
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
