'\" t
.\"     Title: freefoam-foamtovtk
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-FOAMTOVTK" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-foamToVTK \- Legacy VTK file format writer\&.
.SH "SYNOPSIS"
.sp
\fBfreefoam foamToVTK\fR [\-noLinks] [\-srcDoc] [\-noFaceZones] [\-nearCellValue] [\-noPointValues] [\-noInternal] [\-useTimeName] [\-ascii] [\-doc] [\-surfaceFields] [\-mesh \fI<name>\fR] [\-help] [\-cellSet \fI<name>\fR] [\-noZero] [\-excludePatches \fI<patchNames>\fR] [\-time \fI<time>\fR] [\-case \fI<dir>\fR] [\-pointSet \fI<name>\fR] [\-latestTime] [\-fields \fI<fields>\fR] [\-constant] [\-parallel] [\-faceSet \fI<name>\fR] [\-allPatches]
.SH "DESCRIPTION"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
handles volScalar, volVector, pointScalar, pointVector, surfaceScalar fields\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
mesh topo changes\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
both ascii and binary\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
single time step writing\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
write subset only\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
automatic decomposition of cells; polygons on boundary undecomposed since handled by vtk\&.
.RE
.SH "OPTIONS"
.PP
\fB\-ascii\fR
.RS 4
Write VTK data in ASCII format instead of binary\&.
.RE
.PP
\fB\-mesh\fR \fI<name>\fR
.RS 4
Use a different mesh name (instead of \-region)
.RE
.PP
\fB\-fields\fR \fI<fields>\fR
.RS 4
Convert selected fields only\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
     \-fields "( p T U )"
.fi
.if n \{\
.RE
.\}
.sp
The quoting is required to avoid shell expansions and to pass the information as a single argument\&.
.RE
.PP
\fB\-surfaceFields\fR
.RS 4
Write surfaceScalarFields (e\&.g\&., phi)
.RE
.PP
\fB\-cellSet\fR \fI<name>\fR, \fB\-faceSet\fR \fI<name>\fR, \fB\-pointSet\fR \fI<name>\fR
.RS 4
Restrict conversion to the cellSet, faceSet or pointSet\&.
.RE
.PP
\fB\-nearCellValue\fR
.RS 4
Output cell value on patches instead of patch value itself\&.
.RE
.PP
\fB\-noInternal\fR
.RS 4
Do not generate file for mesh, only for patches\&.
.RE
.PP
\fB\-noPointValues\fR
.RS 4
No pointFields\&.
.RE
.PP
\fB\-noFaceZones\fR
.RS 4
No faceZones\&.
.RE
.PP
\fB\-noLinks\fR
.RS 4
(in parallel) do not link processor files to master\&.
.RE
.PP
\fB\-allPatches\fR
.RS 4
Combine all patches into a single file\&.
.RE
.PP
\fB\-excludePatches\fR \fI<patchNames>\fR
.RS 4
Specify patches to exclude\&. For example,
.sp
.if n \{\
.RS 4
.\}
.nf
     \-excludePatches "( inlet_1 inlet_2 )"
.fi
.if n \{\
.RE
.\}
.sp
The quoting is required to avoid shell expansions and to pass the information as a single argument\&.
.RE
.PP
\fB\-useTimeName\fR
.RS 4
use the time index in the VTK file name instead of the time index
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-noZero\fR
.RS 4
Ignore time step 0\&.
.RE
.PP
\fB\-constant\fR
.RS 4
Include the constant directory\&.
.RE
.PP
\fB\-latestTime\fR
.RS 4
Only apply to the latest time step\&.
.RE
.PP
\fB\-time\fR \fI<time>\fR
.RS 4
Apply only to specified time\&.
.RE
.PP
\fB\-parallel\fR
.RS 4
Run in parallel\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "NOTE"
.sp
mesh subset is handled by vtkMesh\&. Slight inconsistency in interpolation: on the internal field it interpolates the whole volfield to the whole\-mesh pointField and then selects only those values it needs for the subMesh (using the fvMeshSubset cellMap(), pointMap() functions)\&. For the patches however it uses the fvMeshSubset\&.interpolate function to directly interpolate the whole\-mesh values onto the subset patch\&.
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
