'\" t
.\"     Title: freefoam-polydualmesh
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-POLYDUALMESH" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-polyDualMesh \- Calculate the dual of a polyMesh\&. Adheres to all the feature and patch edges\&.
.SH "SYNOPSIS"
.sp
\fBfreefoam polyDualMesh\fR [\-doNotPreserveFaceZones] [\-help] [\-srcDoc] [\-case \fI<dir>\fR] [\-doc] [\-overwrite] [\-splitAllFaces] [\-concaveMultiCells]
.SH "DESCRIPTION"
.sp
Detects any boundary edge > angle and creates multiple boundary faces for it\&. Normal behaviour is to have each point become a cell (1\&.5 behaviour)
.SH "OPTIONS"
.PP
\fB\-concaveMultiCells\fR
.RS 4
Creates multiple cells for each point on a concave edge\&. Might limit the amount of distortion on some meshes\&.
.RE
.PP
\fB\-splitAllFaces\fR
.RS 4
Normally only constructs a single face between two cells\&. This single face might be too distorted\&. splitAllFaces will create a single face for every original cell the face passes through\&. The mesh will thus have multiple faces inbetween two cells! (so is not strictly upper\-triangular anymore \- checkMesh will complain)
.RE
.PP
\fB\-doNotPreserveFaceZones\fR
.RS 4
By default all faceZones are preserved by marking all faces, edges and points on them as features\&. The \-doNotPreserveFaceZones disables this behaviour\&.
.RE
.PP
\fB\-overwrite\fR
.RS 4
Overwrite existing data\&.
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "NOTE"
.sp
This is just a driver for meshDualiser\&. Substitute your own simpleMarkFeatures to have different behaviour\&.
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
