'\" t
.\"     Title: freefoam-splitcells
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-SPLITCELLS" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-splitCells \- Utility to split cells with flat faces\&.
.SH "SYNOPSIS"
.sp
\fBfreefoam splitCells\fR \fI<edge angle [0\&.\&.360]>\fR [\-geometry] [\-tol \fI<tolerance>\fR] [\-srcDoc] [\-doc] [\-overwrite] [\-help] [\-set \fI<cellSet name>\fR] [\-case \fI<dir>\fR]
.SH "DESCRIPTION"
.sp
Uses a geometric cut with a plane dividing the edge angle into two so might produce funny cells\&. For hexes it will use by default a cut from edge onto opposite edge (i\&.e\&. purely topological)\&.
.sp
Options: \- split cells from cellSet only \- use geometric cut for hexes as well
.sp
The angle is the angle between two faces sharing an edge as seen from inside each cell\&. So a cube will have all angles 90\&. If you want to split cells with cell centre outside use e\&.g\&. angle 200
.SH "OPTIONS"
.PP
\fI<edge angle [0\&.\&.360]>\fR
.RS 4

\fBTODO\fR
Detailed description of argument\&.
.RE
.PP
\fB\-geometry\fR
.RS 4
Geometry based splitting for hex cells\&.
.RE
.PP
\fB\-tol\fR \fI<tolerance>\fR
.RS 4
Edge snap tolerance\&.
.RE
.PP
\fB\-set\fR \fI<cellSet name>\fR
.RS 4
Cell set to split\&.
.RE
.PP
\fB\-overwrite\fR
.RS 4
Overwrite existing data\&.
.RE
.PP
\fB\-case\fR \fI<dir>\fR
.RS 4
Case directory\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display help message\&.
.RE
.PP
\fB\-doc\fR
.RS 4
Display Doxygen API documentation page for this application\&.
.RE
.PP
\fB\-srcDoc\fR
.RS 4
Display Doxygen source documentation page for this application\&.
.RE
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
