'\" t
.\"     Title: freefoam-job
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/14/2012
.\"    Manual: FreeFOAM Manual
.\"    Source: FreeFOAM 0.1.0
.\"  Language: English
.\"
.TH "FREEFOAM\-JOB" "1" "05/14/2012" "FreeFOAM 0\&.1\&.0" "FreeFOAM Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
freefoam-job \- Runs a FreeFOAM job in the background
.SH "SYNOPSIS"
.sp
\fBfreefoam job\fR [\-case \fI<caseDir>\fR] [\-s] [\-p] [\-hosts \fI<hostFile>\fR] [\-log \fI<logFile>\fR] [\-fg] [\-help] \fI<application>\fR [\fI<options>\fR]
.SH "DESCRIPTION"
.sp
Runs the FreeFOAM application \fI<application>\fR\&. Unless the \fB\-fg\fR option is specified, the job is run in the background (this options is ignored if \fB\-s\fR is specified)\&. The output is written to the file \fIlog\fR, which can be overridden using the \fB\-log\fR option\&. If \fB\-s\fR is specified, the output will also be sent to the screen\&. The \fB\-p\fR option will start the application in parallel using the setting of \fIparRunTemplate\fR in the global \fIcontrolDict\fR (see \fBfreefoam\fR(1))\&. The option \fB\-hosts\fR can be used to provide a file containing a list of host names for the parallel run\&.
.SH "OPTIONS"
.PP
\fB\-case\fR \fI<caseDir>\fR
.RS 4
Specify the case directory\&. Defaults to the current working directory\&.
.RE
.PP
\fB\-s\fR
.RS 4
Also sends output to screen
.RE
.PP
\fB\-p\fR
.RS 4
Run the job in parallel
.RE
.PP
\fB\-hosts\fR \fI<hostFile>\fR
.RS 4
Specify file with host names
.RE
.PP
\fB\-log\fR \fI<logFile>\fR
.RS 4
Specify logfile name for output, defaults to
\fIlog\fR
.RE
.PP
\fB\-fg\fR
.RS 4
Run the job in the foreground (i\&.e\&. don\(cqt background it)\&. This option is ignored if
\fB\-s\fR
is specified\&.
.RE
.PP
\fB\-help\fR
.RS 4
Display an option summary
.RE
.PP
\fI<application>\fR
.RS 4
The application to run
.RE
.PP
\fI<options>\fR
.RS 4
Options to be passed to
\fI<application>\fR
.RE
.SH "SEE ALSO"
.sp
An overview of FreeFOAM is given in \fBfreefoam\fR(1)\&.
.SH "AUTHOR"
.sp
OpenCFD Ltd\&.
.SH "FREEFOAM"
.sp
Part of the \fBfreefoam\fR(1) suite\&.
.SH "COPYRIGHT"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 1991\-2010 OpenCFD Ltd\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Copyright \(co 2008\-2012 Michael Wild\&.
.RE
